# Generated by Django 3.2.5 on 2021-07-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_workout_exercises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['date_custom']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['date_custom']},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['name']},
        ),
    ]
