# Generated by Django 3.2.5 on 2021-07-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_workout_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='main_app.Exercise'),
        ),
    ]
